title: 儿童发展与认知神经科学实验室
description: 致力于儿童认知发展与脑科学研究
baseurl: "/cdcnlab.github.io"  # 替换成您的仓库名
url: "https://xiaokaihan.github.io/cdcnlab.github.io/"  # 替换成您的 GitHub Pages URL

# 主题设置
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "air"  # 使用明亮清新的主题

# 导航菜单
nav_main:
  - title: "首页"
    url: /
  - title: "关于我们"
    url: /about/
    children:
      - title: "实验室介绍"
        url: /about/intro/
      - title: "团队成员"
        url: /about/team/
      - title: "实验室设施"
        url: /about/facilities/
      - title: "合作伙伴"
        url: /about/partners/
  - title: "研究方向"
    url: /research/
    children:
      - title: "儿童发展"
        url: /research/child-development/
      - title: "认知神经科学"
        url: /research/cognitive-neuroscience/
      - title: "跨学科研究"
        url: /research/interdisciplinary/
  - title: "研究成果"
    url: /publications/
  - title: "资源"
    url: /resources/
  - title: "活动与新闻"
    url: /news/
  - title: "加入我们"
    url: /join/
  - title: "联系我们"
    url: /contact/

# 布局设置
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
      sidebar:
        nav: "main"
      toc: true
      toc_sticky: true

# 构建设置
markdown: kramdown 