title: 儿童发展与认知神经科学实验室
subtitle: "Department of Psychology | XXX University"
description: "Understanding the cognitive and neural basis of child development"
baseurl: "/cdcnlab.github.io"  # 替换成您的仓库名
url: "https://xiaokaihan.github.io/cdcnlab.github.io/"  # 替换成您的 GitHub Pages URL

# 主题设置
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "air"  # 改回简洁的亮色主题

# 导航设置 - 参考 Vision Lab 的简洁导航
masthead_links:
  - title: "HOME"
    url: /
  - title: "MEMBERS"
    url: /members/
    children:
      - title: "Principal Investigators"
        url: /members/pi/
      - title: "Postdoctoral Fellows"
        url: /members/postdoc/
      - title: "Graduate Students"
        url: /members/graduate/
      - title: "Research Assistants"
        url: /members/ra/
  - title: "RESEARCH"
    url: /research/
  - title: "PUBLICATIONS"
    url: /publications/
  - title: "PARTICIPATE"
    url: /participate/
  - title: "LAB INFO"
    url: /lab-info/

# 布局设置
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      classes: wide
      author_profile: false
      header:
        overlay_filter: "0.3"
        overlay_color: "#000"
      toc: true
      toc_sticky: true

# 构建设置
markdown: kramdown

# 网站样式
sass:
  style: compressed

# 添加自定义CSS
head_scripts:
  - https://fonts.googleapis.com/css2?family=Noto+Sans+SC:wght@300;400;500;700&display=swap 